export const enum ResponseMessage {
  USER_CREATED = "User account created successfully.",
  DATA_RETRIEVED = "Data retrieved successfully.",
  OPERATION_COMPLETED = "Operation completed successfully.",
  USER_UPDATED = "User profile updated successfully.",
  USER_DELETED = "User account deleted successfully.",
  LOGIN_SUCCESS = "Login successful.",
  LOGOUT_SUCCESS = "Logout successful.",
  PASSWORD_CHANGED = "Password changed successfully.",
  ACCESS_DENIED = "Access denied.",
  NOT_FOUND = "Resource not found.",
  INTERNAL_SERVER_ERROR = "Internal server error. Please try again later.",
  BAD_REQUEST = "Invalid request parameters.",
  UNAUTHORIZED = "Unauthorized access.",
  FORBIDDEN = "Forbidden request.",
  VALIDATION_ERROR = "Validation error.",
  SESSION_EXPIRED = "Session expired. Please log in again.",
  TOO_MANY_REQUESTS = "Too many requests. Please try again later.",
}
